package com.sinjinsong.icourse.core.dao.settlement;

import com.sinjinsong.icourse.core.domain.entity.settlement.institutionSettlementDO;

public interface institutionSettlementDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int insert(institutionSettlementDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    institutionSettlementDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(institutionSettlementDO record);

}