package com.sinjinsong.icourse.core.dao.settlement;

import com.github.pagehelper.Page;
import com.sinjinsong.icourse.core.domain.entity.settlement.InstitutionSettlementDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface InstitutionSettlementDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int insert(InstitutionSettlementDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    InstitutionSettlementDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution_settlement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InstitutionSettlementDO record);


    Page<InstitutionSettlementDO> findAllByInstitutionId(@Param("institutionId") Long institutionId,@Param("pageNum") int pageNum,@Param("pageSize") int pageSize);

    Double sumByInstitutionId(@Param("institutionId") Long institutionId);
}