package com.sinjinsong.icourse.core.domain.entity.vip;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class VIPDiscountDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_discount.vip_level
     *
     * @mbggenerated
     */
    private Integer vipLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_discount.discount
     *
     * @mbggenerated
     */
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_discount.least_consumptions
     *
     * @mbggenerated
     */
    private Double leastConsumptions;
}