package com.sinjinsong.icourse.core.dao.pay;

import com.sinjinsong.icourse.core.domain.entity.pay.AlipayDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AlipayDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String alipayUsername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int insert(AlipayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    AlipayDO selectByPrimaryKey(String alipayUsername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayDO record);
    AlipayDO findByUserId(@Param("studentId") Long userId);
}