package com.sinjinsong.icourse.core.dao.pay;

import com.sinjinsong.icourse.core.domain.entity.pay.AlipayDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AlipayDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int insert(AlipayDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    AlipayDO selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alipay
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AlipayDO record);
}