package com.sinjinsong.icourse.core.domain.entity.pay;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AlipayDO {
    @NotNull
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.alipay_username
     *
     * @mbggenerated
     */
    @NotNull
    private String alipayUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.balance
     *
     * @mbggenerated
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.payment_password
     *
     * @mbggenerated
     */
    @NotNull
    private String paymentPassword;
    
}