package com.sinjinsong.icourse.core.domain.entity.pay;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AlipayDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.alipay_username
     *
     * @mbggenerated
     */
    private String alipayUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.balance
     *
     * @mbggenerated
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alipay.payment_password
     *
     * @mbggenerated
     */
    private String paymentPassword;

}