package com.sinjinsong.icourse.core.domain.entity.pay;

import com.sinjinsong.icourse.core.domain.entity.user.UserDO;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class BalanceDO implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.security
     *
     * @mbggenerated
     */
    private UserDO user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column balance.balance
     *
     * @mbggenerated
     */
    private Double balance;
    private String paymentPassword;
}