package com.sinjinsong.icourse.core.domain.entity.institution;

import com.sinjinsong.icourse.core.domain.entity.role.RoleDO;
import com.sinjinsong.icourse.core.enumeration.institution.InstitutionStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class InstitutionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.username
     *
     * @mbggenerated
     */
    private String username;
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.status
     *
     * @mbggenerated
     */
    private InstitutionStatus status;
    private List<RoleDO> roles;
}