package com.sinjinsong.icourse.core.domain.entity.institution;

import com.sinjinsong.icourse.core.domain.entity.role.RoleDO;
import com.sinjinsong.icourse.core.enumeration.institution.InstitutionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InstitutionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.username
     *
     * @mbggenerated
     */
    @NotNull
    private String username;
    @NotNull
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.location
     *
     * @mbggenerated
     */
    @NotNull
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.description
     *
     * @mbggenerated
     */
    @NotNull
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column institution.status
     *
     * @mbggenerated
     */
    private InstitutionStatus status;
    private List<RoleDO> roles;
}