package com.sinjinsong.icourse.core.dao.product;

import com.sinjinsong.icourse.core.domain.entity.product.ProductCategoryDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface ProductCategoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated
     */
    int insert(ProductCategoryDO record);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated
     */
    ProductCategoryDO selectByPrimaryKey(Long id);
    ProductCategoryDO selectSimpleByPrimaryKey(Long id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductCategoryDO record);

    List<ProductCategoryDO> findAll();
    List<ProductCategoryDO> findAllWithOutProducts();
    List<ProductCategoryDO> findOnBoard();
}