package com.sinjinsong.icourse.core.dao.institution;

import com.github.pagehelper.Page;
import com.sinjinsong.icourse.core.domain.entity.institution.InstitutionDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface InstitutionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated
     */
    int insert(InstitutionDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated
     */
    InstitutionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table institution
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InstitutionDO record);

    InstitutionDO findByUsername(@Param("username") String username);


    Page<InstitutionDO> findAll(@Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
}