# Tomcat
server:
    port: 8080
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
# mysql
spring:
  # 环境 dev|test|pro
  profiles:
      active: dev
  output:
    ansi:
      enabled: detect #配置输出console的ide中的配色
  # jackson时间格式化
  jackson:
      time-zone: GMT+8
  #    default-property-inclusion: non_null    #忽略null字段
  #国际化        
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    fallback-to-system-locale: true
  aop:
    auto: true
    proxy-target-class: true 
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html # ;charset=<encoding> is added
    cache: false
    #邮箱
  mail:
    host: smtp.163.com
    port: 25
    username: songxinjianzx@163.com
    password: 201529sxj
    default-encoding: utf-8
    properties: 
      mail:
        smtp:
          auth: true
          timeout: 25000
## Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
# Mybatis PageHelper
pagehelper:
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  auto-runtime-dialect: true