package com.sinjinsong.icourse.core.dao.manager;

import com.sinjinsong.icourse.core.domain.entity.manager.ManagerDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface ManagerDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated
     */
    int insert(ManagerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated
     */
    ManagerDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ManagerDO record);

    ManagerDO findManager();

    ManagerDO findByUsername(@Param("username") String username);

}