package com.sinjinsong.icourse.core.dao.course;

import com.github.pagehelper.Page;
import com.sinjinsong.icourse.core.domain.entity.course.StudyRecordDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StudyRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int insert(StudyRecordDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    StudyRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudyRecordDO record);

    Page<StudyRecordDO> findAllByStudentId(@Param("studentId") Long studentId, @Param("pageNum") int pageNum, @Param("pageSize") int pageSize);

    Page<StudyRecordDO> findAllByClassId(@Param("classId") Long classId, @Param("pageNum") int pageNum, @Param("pageSize") int pageSize);
    
    StudyRecordDO findByOrderId(@Param("orderId") Long orderId);
}