package com.sinjinsong.icourse.core.dao.course;

import com.sinjinsong.icourse.core.domain.entity.course.StudyRecordDO;

public interface StudyRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int insert(StudyRecordDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    StudyRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table study_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StudyRecordDO record);

}