package com.sinjinsong.icourse.core.domain.entity.order;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.sinjinsong.icourse.common.properties.DateTimeProperties;
import com.sinjinsong.icourse.core.domain.entity.course.ClassDO;
import com.sinjinsong.icourse.core.domain.entity.institution.InstitutionDO;
import com.sinjinsong.icourse.core.domain.entity.student.StudentDO;
import com.sinjinsong.icourse.core.enumeration.order.OrderStatus;
import com.sinjinsong.icourse.core.enumeration.order.PayType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;
import java.time.LocalDateTime;
@Data
@NoArgsConstructor
@AllArgsConstructor
public class OrderDO {
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.student_id
     *
     * @mbggenerated
     */
    private StudentDO student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.class_id
     *
     * @mbggenerated
     */
    @NotNull
    private ClassDO classDO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.place_time
     *
     * @mbggenerated
     */
    @JsonFormat(pattern = DateTimeProperties.LOCAL_DATE_TIME_PATTERN)
    private LocalDateTime placeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.price
     *
     * @mbggenerated
     */
    @NotNull
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_status
     *
     * @mbggenerated
     */
    private OrderStatus status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.discount
     *
     * @mbggenerated
     */
    @NotNull
    private Double discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_type
     *
     * @mbggenerated
     */
    @NotNull
    private PayType payType;
    private InstitutionDO institution;
    private Boolean isSettled;
}